-- The 1PM Club: schema, policies, seed data and authoritative ordering RPC.
create extension if not exists pgcrypto;

create type public.user_role as enum ('customer', 'admin');
create type public.order_method as enum ('pickup', 'delivery');
create type public.time_slot as enum ('morning', 'lunch');
create type public.order_status as enum ('pending', 'confirmed', 'preparing', 'ready_for_pickup', 'to_be_delivered', 'completed', 'rejected', 'cancelled');
create type public.payment_status as enum ('unpaid', 'paid');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 100),
  email text not null check (email = lower(email)),
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, sort_order int not null default 0, is_active boolean not null default true);
create table public.products (id uuid primary key default gen_random_uuid(), category_id uuid not null references public.categories(id), name text not null unique, price_centavos int not null check(price_centavos >= 0), is_available boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.addons (id uuid primary key default gen_random_uuid(), name text not null unique, price_centavos int not null check(price_centavos >= 0), is_available boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.departments (id uuid primary key default gen_random_uuid(), name text not null unique, is_active boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.business_settings (id boolean primary key default true check(id), accepting_orders boolean not null default true, morning_cutoff time not null default '10:00', lunch_cutoff time not null default '13:30', slot_capacity int not null default 15 check(slot_capacity > 0), timezone text not null default 'Asia/Manila' check(timezone = 'Asia/Manila'), payment_qr_url text, updated_at timestamptz not null default now());
create sequence public.order_number_seq start 100000;
create table public.orders (
  id uuid primary key default gen_random_uuid(), order_number bigint not null unique default nextval('public.order_number_seq'), customer_id uuid references public.profiles(id), customer_name_snapshot text not null, customer_email_snapshot text not null, guest_access_token_hash text,
  order_method public.order_method not null, department_id uuid references public.departments(id), department_name_snapshot text,
  fulfillment_date date not null, time_slot public.time_slot not null, order_status public.order_status not null default 'pending', payment_status public.payment_status not null default 'unpaid',
  subtotal_centavos int not null check(subtotal_centavos >= 0), total_centavos int not null check(total_centavos >= 0), customer_note text check(char_length(customer_note) <= 300), rejection_message text, payment_marked_paid_at timestamptz, payment_marked_paid_by uuid references public.profiles(id), ready_email_sent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), confirmed_at timestamptz, completed_at timestamptz, cancelled_at timestamptz,
  check ((order_method = 'delivery' and department_id is not null and department_name_snapshot is not null) or (order_method = 'pickup' and department_id is null and department_name_snapshot is null)),
  check ((customer_id is null and guest_access_token_hash is not null) or (customer_id is not null and guest_access_token_hash is null))
);
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id), product_name_snapshot text not null, unit_price_snapshot_centavos int not null check(unit_price_snapshot_centavos >= 0), quantity int not null check(quantity >= 1), subtotal_centavos int not null check(subtotal_centavos >= 0));
create table public.order_item_addons (id uuid primary key default gen_random_uuid(), order_item_id uuid not null references public.order_items(id) on delete cascade, addon_id uuid references public.addons(id), addon_name_snapshot text not null, addon_price_snapshot_centavos int not null check(addon_price_snapshot_centavos >= 0));
create table public.notifications (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.email_logs (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, email_type text not null, recipient text not null, provider text not null default 'resend', provider_message_id text, status text not null, error_message text, created_at timestamptz not null default now(), sent_at timestamptz, unique(order_id, email_type));

create index orders_customer_idx on public.orders(customer_id, created_at desc); create index orders_fulfillment_slot_idx on public.orders(fulfillment_date, time_slot, order_status); create index orders_status_idx on public.orders(order_status); create index orders_payment_idx on public.orders(payment_status); create index products_category_available_idx on public.products(category_id, is_available); create index departments_active_idx on public.departments(is_active); create index order_items_order_idx on public.order_items(order_id); create index order_item_addons_item_idx on public.order_item_addons(order_item_id);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at(); create trigger products_updated before update on public.products for each row execute function public.set_updated_at(); create trigger addons_updated before update on public.addons for each row execute function public.set_updated_at(); create trigger departments_updated before update on public.departments for each row execute function public.set_updated_at(); create trigger orders_updated before update on public.orders for each row execute function public.set_updated_at();
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id,name,email) values (new.id, coalesce(nullif(new.raw_user_meta_data->>'name',''), split_part(new.email,'@',1)), lower(new.email)); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.addons enable row level security; alter table public.departments enable row level security; alter table public.business_settings enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.order_item_addons enable row level security; alter table public.notifications enable row level security; alter table public.email_logs enable row level security;
create policy "profiles read own" on public.profiles for select using (id = auth.uid() or public.is_admin()); create policy "profiles update own" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid() and role = (select role from public.profiles where id = auth.uid()));
create policy "catalogue public read" on public.categories for select using (true); create policy "products public read" on public.products for select using (true); create policy "addons public read" on public.addons for select using (true); create policy "departments active read" on public.departments for select using (is_active or public.is_admin()); create policy "settings public read" on public.business_settings for select using (true);
create policy "admin categories" on public.categories for all using (public.is_admin()) with check (public.is_admin()); create policy "admin products" on public.products for all using (public.is_admin()) with check (public.is_admin()); create policy "admin addons" on public.addons for all using (public.is_admin()) with check (public.is_admin()); create policy "admin departments" on public.departments for all using (public.is_admin()) with check (public.is_admin()); create policy "admin settings" on public.business_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "orders own or admin" on public.orders for select using (customer_id = auth.uid() or public.is_admin()); create policy "items own or admin" on public.order_items for select using (exists(select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_admin()))); create policy "item addons own or admin" on public.order_item_addons for select using (exists(select 1 from public.order_items i join public.orders o on o.id=i.order_id where i.id = order_item_id and (o.customer_id=auth.uid() or public.is_admin()))); create policy "notifications own" on public.notifications for select using(profile_id=auth.uid()); create policy "notifications update own" on public.notifications for update using(profile_id=auth.uid()) with check(profile_id=auth.uid()); create policy "email logs admin" on public.email_logs for select using(public.is_admin());

create or replace function public.get_slot_capacity(p_fulfillment_date date) returns table(time_slot public.time_slot, reserved_cups int, capacity int) language sql stable security definer set search_path = public as $$ with slots as (select unnest(enum_range(null::public.time_slot)) as slot), used as (select o.time_slot, coalesce(sum(i.quantity),0)::int as cups from public.orders o join public.order_items i on i.order_id=o.id where o.fulfillment_date=p_fulfillment_date and o.order_status in ('pending','confirmed','preparing','ready_for_pickup','to_be_delivered') group by o.time_slot) select slots.slot, coalesce(used.cups,0), settings.slot_capacity from slots cross join public.business_settings settings left join used on used.time_slot=slots.slot where settings.id=true; $$;

create or replace function public.create_order(p_customer_name text, p_customer_email text, p_order_method public.order_method, p_department_id uuid, p_fulfillment_date date, p_time_slot public.time_slot, p_customer_note text, p_items jsonb) returns table(order_number bigint, guest_access_token text) language plpgsql security definer set search_path = public as $$
declare v_settings public.business_settings%rowtype; v_today date := (now() at time zone 'Asia/Manila')::date; v_now time := (now() at time zone 'Asia/Manila')::time; v_days int; v_cups int; v_used int; v_subtotal int := 0; v_order public.orders%rowtype; v_item jsonb; v_product public.products%rowtype; v_addon public.addons%rowtype; v_item_id uuid; v_addon_total int; v_department public.departments%rowtype; v_token text; v_profile public.profiles%rowtype;
begin
  select * into v_settings from public.business_settings where id=true; if not found or not v_settings.accepting_orders then raise exception 'ORDERS_CLOSED'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'INVALID_ITEMS'; end if;
  v_days := p_fulfillment_date - v_today;
  if v_days < 0 or v_days > 7 or extract(isodow from p_fulfillment_date) not in (1,2,3) then raise exception 'SCHEDULE_INVALID'; end if;
  if v_days = 0 then if (p_time_slot='morning' and v_now >= v_settings.morning_cutoff) or (p_time_slot='lunch' and v_now >= v_settings.lunch_cutoff) then raise exception 'SLOT_CLOSED'; end if;
  elsif (extract(isodow from p_fulfillment_date)=1 and v_days not between 1 and 3) or (extract(isodow from p_fulfillment_date)=2 and v_days <> 1) or (extract(isodow from p_fulfillment_date)=3 and v_days <> 1) then raise exception 'SCHEDULE_INVALID'; end if;
  select coalesce(sum((item->>'quantity')::int),0) into v_cups from jsonb_array_elements(p_items) item; if v_cups < 1 or v_cups > v_settings.slot_capacity then raise exception 'INVALID_QUANTITY'; end if;
  if p_order_method='delivery' then select * into v_department from public.departments where id=p_department_id and is_active; if not found then raise exception 'INVALID_DEPARTMENT'; end if; elsif p_department_id is not null then raise exception 'INVALID_DEPARTMENT'; end if;
  perform pg_advisory_xact_lock(hashtext(p_fulfillment_date::text || ':' || p_time_slot::text));
  select coalesce(sum(i.quantity),0) into v_used from public.orders o join public.order_items i on i.order_id=o.id where o.fulfillment_date=p_fulfillment_date and o.time_slot=p_time_slot and o.order_status in ('pending','confirmed','preparing','ready_for_pickup','to_be_delivered'); if v_used + v_cups > v_settings.slot_capacity then raise exception 'CAPACITY_FULL'; end if;
  if auth.uid() is not null then select * into v_profile from public.profiles where id=auth.uid(); if not found then raise exception 'PROFILE_REQUIRED'; end if; else if char_length(trim(p_customer_name)) < 2 or lower(trim(p_customer_email)) !~ '^[^@]+@[^@]+\.[^@]+$' then raise exception 'INVALID_GUEST'; end if; v_token := encode(extensions.gen_random_bytes(32),'hex'); end if;
  foreach v_item in array (select array_agg(value) from jsonb_array_elements(p_items)) loop select * into v_product from public.products where id=(v_item->>'product_id')::uuid and is_available; if not found then raise exception 'PRODUCT_UNAVAILABLE'; end if; v_addon_total:=0; for v_addon in select * from public.addons where id in (select value::uuid from jsonb_array_elements_text(coalesce(v_item->'addon_ids','[]'::jsonb))) loop if not v_addon.is_available then raise exception 'ADDON_UNAVAILABLE'; end if; v_addon_total:=v_addon_total+v_addon.price_centavos; end loop; if (select count(*) from jsonb_array_elements_text(coalesce(v_item->'addon_ids','[]'::jsonb))) <> (select count(*) from public.addons where id in (select value::uuid from jsonb_array_elements_text(coalesce(v_item->'addon_ids','[]'::jsonb)))) then raise exception 'INVALID_ADDON'; end if; v_subtotal:=v_subtotal+(v_product.price_centavos+v_addon_total)*(v_item->>'quantity')::int; end loop;
  insert into public.orders(customer_id,customer_name_snapshot,customer_email_snapshot,guest_access_token_hash,order_method,department_id,department_name_snapshot,fulfillment_date,time_slot,subtotal_centavos,total_centavos,customer_note) values (auth.uid(),coalesce(v_profile.name,trim(p_customer_name)),coalesce(v_profile.email,lower(trim(p_customer_email))),case when v_token is null then null else extensions.crypt(v_token,extensions.gen_salt('bf')) end,p_order_method,p_department_id,case when p_order_method='delivery' then v_department.name else null end,p_fulfillment_date,p_time_slot,v_subtotal,v_subtotal,nullif(trim(p_customer_note),'')) returning * into v_order;
  foreach v_item in array (select array_agg(value) from jsonb_array_elements(p_items)) loop select * into v_product from public.products where id=(v_item->>'product_id')::uuid; insert into public.order_items(order_id,product_id,product_name_snapshot,unit_price_snapshot_centavos,quantity,subtotal_centavos) values(v_order.id,v_product.id,v_product.name,v_product.price_centavos,(v_item->>'quantity')::int,(v_product.price_centavos+(select coalesce(sum(price_centavos),0) from public.addons where id in (select value::uuid from jsonb_array_elements_text(coalesce(v_item->'addon_ids','[]'::jsonb)))))*(v_item->>'quantity')::int) returning id into v_item_id; insert into public.order_item_addons(order_item_id,addon_id,addon_name_snapshot,addon_price_snapshot_centavos) select v_item_id,a.id,a.name,a.price_centavos from public.addons a where a.id in (select value::uuid from jsonb_array_elements_text(coalesce(v_item->'addon_ids','[]'::jsonb))); end loop;
  return query select v_order.order_number, v_token;
end; $$;

create or replace function public.cancel_own_pending_order(p_order_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.orders set order_status='cancelled', cancelled_at=now() where id=p_order_id and customer_id=auth.uid() and order_status='pending'; if not found then raise exception 'CANNOT_CANCEL'; end if; end; $$;
create or replace function public.admin_update_order(p_order_id uuid,p_status public.order_status,p_payment_status public.payment_status,p_rejection_message text) returns void language plpgsql security definer set search_path=public as $$ declare v_old public.orders%rowtype; begin if not public.is_admin() then raise exception 'NOT_AUTHORIZED'; end if; select * into v_old from public.orders where id=p_order_id for update; if not found then raise exception 'NOT_FOUND'; end if; if p_payment_status is not null then update public.orders set payment_status=p_payment_status,payment_marked_paid_at=case when p_payment_status='paid' then now() else null end,payment_marked_paid_by=case when p_payment_status='paid' then auth.uid() else null end where id=p_order_id; end if; if p_status is not null and p_status<>v_old.order_status then if not ((v_old.order_status='pending' and p_status in ('confirmed','rejected')) or (v_old.order_status='confirmed' and p_status='preparing') or (v_old.order_status='preparing' and p_status in ('ready_for_pickup','to_be_delivered')) or (v_old.order_status in ('ready_for_pickup','to_be_delivered') and p_status='completed')) then raise exception 'INVALID_STATUS_TRANSITION'; end if; update public.orders set order_status=p_status,confirmed_at=case when p_status='confirmed' then now() else confirmed_at end,completed_at=case when p_status='completed' then now() else completed_at end,rejection_message=case when p_status='rejected' then nullif(trim(p_rejection_message),'') else rejection_message end where id=p_order_id; end if; end; $$;
create or replace function public.get_guest_order(p_order_number bigint,p_token text) returns table(id uuid,order_number bigint,customer_name_snapshot text,fulfillment_date date,time_slot public.time_slot,order_method public.order_method,department_name_snapshot text,order_status public.order_status,payment_status public.payment_status,total_centavos int,created_at timestamptz) language sql security definer set search_path=public as $$ select o.id,o.order_number,o.customer_name_snapshot,o.fulfillment_date,o.time_slot,o.order_method,o.department_name_snapshot,o.order_status,o.payment_status,o.total_centavos,o.created_at from public.orders o where o.order_number=p_order_number and o.customer_id is null and extensions.crypt(p_token,o.guest_access_token_hash)=o.guest_access_token_hash; $$;

insert into public.categories(name,slug,sort_order) values ('Coffee','coffee',1),('Matcha','matcha',2),('Hōjicha','hojicha',3);
insert into public.products(category_id,name,price_centavos,sort_order) select id,n,p,s from public.categories join (values ('coffee','Iced Shaken Oat',7500,1),('coffee','Vanilla Brown',9000,2),('coffee','Blondie',9500,3),('coffee','Caramel Oat',9500,4),('coffee','Salted Cream Vanilla',11000,5),('matcha','Zen Matcha',15000,1),('matcha','Matchaña',15000,2),('matcha','Earl Grey Fusion',17000,3),('matcha','Salted Cloud',18000,4),('matcha','Matcha Blanc',18000,5),('hojicha','Hōjicha Latte',12000,1),('hojicha','Spanish Hōji',12000,2),('hojicha','Hōji Blanc',15000,3),('hojicha','Sea Salt Cream',16000,4)) as menu(slug,n,p,s) using(slug);
insert into public.addons(name,price_centavos,sort_order) values ('Extra Coffee',1000,1),('Matcha',2500,2),('Hōjicha',1500,3),('Agave Syrup',1500,4),('Stevia/Splenda',500,5),('Extra Caramel',2000,6),('Extra White Choco',2500,7);
insert into public.business_settings(id) values(true);
grant execute on function public.get_slot_capacity(date) to anon, authenticated; grant execute on function public.create_order(text,text,public.order_method,uuid,date,public.time_slot,text,jsonb) to anon, authenticated; grant execute on function public.get_guest_order(bigint,text) to anon, authenticated; grant execute on function public.cancel_own_pending_order(uuid) to authenticated; grant execute on function public.admin_update_order(uuid,public.order_status,public.payment_status,text) to authenticated;
